### ISSUE TITLE
How do people join organizations?

### ISSUE THREAD

**Issue by MarcDoughty** [BrownUniversity/New-Users-Read-Me#4]
I'm hoping we can provide a bit of information on the process to join an organization to this. Is there a proper procedure for that? I'd like to be able to send this to student workers as a one-stop doc for getting onboarded.

**Comment by MarcDoughty** [comment]
https://github.com/orgs/BrownUniversity/sso/sign_up

**Comment by brtduvally** [comment]
We will be disabling SSO in the near future due to issues with how GitHub handles SAML, so we don't want to include this. It wasn't included originally because this repo is only visible to people who have already joined the org.

Closing this issue.
