### ISSUE TITLE
Provide links to SSO / key-generation instructions

### ISSUE THREAD

**Issue by MarcDoughty** [BrownUniversity/New-Users-Read-Me#5]
Add info to get users up and running with a trusted key so they can use the command line.

**Comment by MarcDoughty** [comment]
1. You may want to start using a password manager. Brown Licenses LastPass for faculty and staff.
2. We follow the steps in this guide: https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh .
3. Use a modern algorithm: **# ssh-keygen -t ed25519 -C "your_email@brown.edu**" , and choose a passphrase that is complex and NOT the same as your password.
4. After you set this up, you can use git from the command line (or other apps) using SSH instead of HTTPS:  https://help.github.com/en/github/using-git/which-remote-url-should-i-use

**Comment by brtduvally** [comment]
The link to GitHub's instructions in your pull request is perfect. 

We are not going to provide info to SSO since we are removing it soon.
